
project_id = "ncbbjlduisavvxyscxbk"

[api]
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.clever-api]
verify_jwt = false

[functions.tspay-handler]
verify_jwt = false

[functions.otp-handler]
verify_jwt = false
